# Generated by Django 3.1.4 on 2020-12-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
