# Generated by Django 3.1.4 on 2020-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20201202_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='covid_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
