# Generated by Django 3.1.4 on 2020-12-02 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0007_auto_20201203_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), null=True, size=None)),
                ('info', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), null=True, size=None)),
                ('photo_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('res_items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('total_restaurants', models.IntegerField(null=True)),
            ],
        ),
    ]
